// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMIRe95GOCkMoxfuBc30sTTK9ePi_Apno',
    appId: '1:819980564424:web:31324b5f32445139b572fd',
    messagingSenderId: '819980564424',
    projectId: 'poc-signon',
    authDomain: 'poc-signon.firebaseapp.com',
    databaseURL: 'https://poc-signon-default-rtdb.firebaseio.com',
    storageBucket: 'poc-signon.appspot.com',
    measurementId: 'G-BBJHQK4LWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHVzWgxsVCqST7N4jOMHggDH3vfBmDXg',
    appId: '1:819980564424:android:8f0154106af47785b572fd',
    messagingSenderId: '819980564424',
    projectId: 'poc-signon',
    databaseURL: 'https://poc-signon-default-rtdb.firebaseio.com',
    storageBucket: 'poc-signon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZwGOilRHHvwQwX1ERDLQRW8lXHbH3TFE',
    appId: '1:819980564424:ios:c96b4171d6a12a80b572fd',
    messagingSenderId: '819980564424',
    projectId: 'poc-signon',
    databaseURL: 'https://poc-signon-default-rtdb.firebaseio.com',
    storageBucket: 'poc-signon.appspot.com',
    iosClientId: '819980564424-0hq8p31v76mv3l17gsfhjujo3sl6mdtg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocRegTask',
  );
}
